[general]
import = ["~/.config/alacritty/themes/788bc5.toml"]

[env]
TERM = "alacritty"

[window]
startup_mode = "Maximized"
opacity = 0.8
blur = true

[scrolling]
history = 10000

[font]
size = 14.0
normal = { family = "Moralerspace Neon", style = "Regular" }
bold = { family = "Moralerspace Neon", style = "Bold" }
italic = { family = "Moralerspace Neon", style = "Italic" }
bold_italic = { family = "Moralerspace Neon", style = "Bold Italic" }

[colors]
# See: 788bc5.toml
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Beam", blinking = "Off" }

[terminal]
shell = { program = "/opt/homebrew/bin/zsh", args = ["--no-global-rcs"] }

[mouse]
hide_when_typing = true
