[colors.primary]
background = "#161011"
foreground = "#e4dbdd"
dim_foreground = "#867e7f"

[colors.normal]
black = "#2d2728"
red = "#be796c"
green = "#679d6e"
yellow = "#998f4b"
blue = "#788bc5"
magenta = "#aa7aab"
cyan = "#3c9ea4"
white = "#c4bbbd"

[colors.bright]
black = "#554e4f"
red = "#e57461"
green = "#52b264"
yellow = "#ae9b00"
blue = "#7793f2"
magenta = "#c778c9"
cyan = "#00b3be"
white = "#e4dbdd"

[colors.dim]
black = "#211b1c"
red = "#7a4238"
green = "#326039"
yellow = "#5e5517"
blue = "#425181"
magenta = "#6b436c"
cyan = "#006166"
white = "#867e7f"
